minimum_pre_commit_version: 3.0.0
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: debug-statements

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)

-   repo: local
    hooks:
    -   id: clang-format-with-version-check
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./scripts/clang_format.hook -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx)$

-   repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: v0.6.9
    hooks:
    -   id: cmake-format

-   repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
    -   id: hadolint
        args: ['--ignore=SC1071', '--ignore=DL3008']
        types: [dockerfile]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
        -   mdformat-frontmatter
        -   mdformat-footnote
        -   mdformat-tables

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
